# example of a configuration file for PicoScope 2000 Series
PSmodel: 3000a

# channel configuration 
picoChannels: [A, B, C]
ChanRanges: [0.2, 0.2, 0.2]
ChanOffsets: [0.15, 0.15, 0.15]
sampleTime: 0.00002
Nsamples: 5000

# trigger
trgActive: true  # true to activate
trgChan: A
trgThr: -0.04
pretrig: 0.05
trgTyp: Falling
trgTO: 2000  # time-out

# signal generator 
#frqSG: 100.E+3 # put 0. do disable

